# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        exclude: tap_spreadsheets_anywhere/test/sample-jsonl.json
        args:
          - --autofix
          - --indent
          - '2'
      - id: trailing-whitespace
  - repo: https://github.com/lyz-code/yamlfix.git
    rev: 1.9.0
    hooks:
      - id: yamlfix
        exclude: templates
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        exclude: templates
        args:
          - --format
          - parsable
          - --strict
